### ISSUE TITLE
Play Folder (that is not in the database)

### ISSUE THREAD

**Issue by MakerMeik** [z000ao8q/audios#552]
I would appreciate a simple way to play entire folders. I am aware of the "Folder" sorting method, but this only shows the database contents at the end. 

However, I would prefer to play Nextcloud folders via the normal file browser using a "Play folder" or "Add to playlist" button. And that includes folders that are not in the database and should not appear there if possible. E.g. because the folder is only temporary.

I can click and play single files at the moment. But the next file is currently not played automatically. And of course there is no shuffle either.

In my case it is actually so that I have a directory with many albums, which I organize as intended in the database. But occasionally I don't want to listen to albums, but a colorful mix all over the place. For this purpose I have a separate folder that consists only of very many individual songs. If I would integrate this folder into the database it would not be usable anymore, because too many artists with only one song each would appear.

The option "Play folder" together with a shuffle button would solve the problem for me.

**Comment by Rello** [comment]
Hello,
the files-app player was removed since Nextcloud offered their own player out of the box. There would only be compatibility issues with having both in parallel.

Can you open the request there?

**Comment by MakerMeik** [comment]
OK, I'll try it this way. Thanks for your feedback.
