### ISSUE TITLE
[Feature Request] user interface improvements

### ISSUE THREAD

**Issue by marcelklehr** [z000ao8q/audios#555]
Hi @Rello 

After our conversation recently, I've tried to come up with a layout that I'd find more intuitive.
This is my draft so far
![Untitled Diagram drawio](https://user-images.githubusercontent.com/986878/138137213-6025765f-6dc7-41a7-a98c-bac89389bd2f.png)

Clicking on the title of the currently playing song could open a sidebar with the current queue (see #536).

My reasoning is that by putting the main categories into an actual list, more screen estate is used and less clicks are necessary, while making the UI easier to explore visually. The second column then displays the actual entries of that category, possibly allowing to create new ones (in case of playlists). I moved the player UI to the bottom of the page as that's where most players have it these days, but it also makes sense since you first need to select a song/album and can only then play it. I'd move the view switcher to the top right as a button, creating a bit of a toolbar, where you could also add a sort-order switcher or similar things.

let me know what you think :)
Cheers

**Comment by tomasbrchan** [comment]
In current view a mainly miss simple Play/Pause button and Next / Previous buttons. It took me really some time to find that I can click on the track again to pause it. Not intuitive at all.

Oh, it appears now. I have no idea where the bug was, but I see the buttons now. Even shuffle and repeat buttons are now visible.

**Comment by obel1x** [comment]
good idea. please mind that  for larger collections "album-artist" tag may be more important than artist.

Also please consider, that there may be more entries, than visible on the screen. in my current view, there is NO way to scroll the list down, making it impossible to find an artist not on the first screen by scrolling.
(actual nextcloudstable and updated app)

an next improvement: make all id3tags found selectable in the column-selections :)

**Comment by Rello** [comment]
Hello,
thank you for this request. I understand the requirement, but the time invested in the app is currently limited due to other priorities.
