### ISSUE TITLE
remove recognize code

### ISSUE THREAD

**Issue by matiasdelellis** [z000ao8q/audios#560]
Hi @Rello 

I am looking some code for inspiration to implement something and just see that:

https://github.com/Rello/audioplayer/blob/7601d7d51853e4c20ad0670dcdcc9aa0953812a8/lib/Service/TagManager.php#L12

Replace with Audio Player.. 😉

**Comment by Rello** [comment]
Hello,
actually this constant is not relevant at all. will remove it.
thank you for the hint

**Comment by Rello** [comment]
update released
