### ISSUE TITLE
[Feature Request] Add please sort by date

### ISSUE THREAD

**Issue by lonagi** [z000ao8q/audios#561]
In audioplayer you can add an additional column like "file createad at". So, if I click it, It sorts

**Comment by Rello** [comment]
Hello,
this is not possible with AP at the moment.
this would require quite some redesign to make a column-selector in the list view; save the settings; fine-tune the search queries in the background for performance, ...

As the use case is very limited, I don´t have the resources to support this at the moment.

thank you...
