### ISSUE TITLE
Audio files missing in listings after update to 3.2.3

### ISSUE THREAD

**Issue by ksaro1** [z000ao8q/audios#564]
### Actual behavior
None of the audio files are listed in audioplayer any more, even though they exist and are supported file types.

### Steps to reproduce the behavior
1. update audioplayer on nextcloud 23.0.0.10 to 3.2.3

### Additional information (optional)
pi@raspberrypi:~ $ ls  /media/pi/Seagate\ Backup\ Plus\ Drive/WebData/Family/*.m4a|wc -l
183
![Screenshot 2021-12-27 at 15 58 56](https://user-images.githubusercontent.com/76841205/147488589-508c5065-3c48-46af-9735-7893eb1d47b3.png)

![Screenshot 2021-12-27 at 15 58 15](https://user-images.githubusercontent.com/76841205/147488629-19fec97b-99b9-42db-8467-8b4738fceaff.png)
![Screenshot 2021-12-27 at 16 08 33](https://user-images.githubusercontent.com/76841205/147488764-f52abf5c-520f-455d-93b0-fcb1d8a130a1.png)

**Nextcloud/ownCloud version:** (see `/status.php`)
23.0.0.10
**Audio Player version:** (see `/settings/apps`)
3.2.3
#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

</details>

**Comment by Rello** [comment]
hi
anything in the logs?

**Comment by Rello** [comment]
ok, got it. related to this one
https://github.com/Rello/audioplayer/pull/563

will be fixed in some minutes

**Comment by Rello** [comment]
update released...

**Comment by rakekniven** [comment]
Same here after updating to v3.2.3

Confirmed v3.2.4 fixed it.

**Comment by Rello** [comment]
yes. sorry for this.
somehow. an error got committed but it was correct in the local testing instance

**Comment by ksaro1** [comment]
Still not working for me

**Comment by ksaro1** [comment]
![Screenshot 2021-12-27 at 23 53 52](https://user-images.githubusercontent.com/76841205/147514442-e7ee9fdb-af87-4748-b110-732e5dece343.png)
![Screenshot 2021-12-27 at 15 58 56](https://user-images.githubusercontent.com/76841205/147514461-f8dd4403-2f56-4210-b033-4e61f0e6bbe1.png)

**Comment by ksaro1** [comment]
Never mind - it is working now. Sorry...
