### ISSUE TITLE
Music found but not shown

### ISSUE THREAD

**Issue by shamiv** [z000ao8q/audios#565]
### Actual behavior
The webpage of the Audio Player does not show any music, even after a successful scan.

### Steps to reproduce the behavior
1. Deactive and remove app from admin account
1. Re-install Audio Player
2. Reset library (nextcloud.occ audioplayer:reset user -vvv)
2. Set default scan folder in GUI
3. Scan for music (in GUI or occ). Songs and albums found.
4. Nothing shows except the basic structure of the Audio Player.

### Additional information (optional)
- I am running the Nextcloud snap.

**Nextcloud/ownCloud version:** 
22.2.3.0

**Audio Player version:**
3.2.3

#### Nextcloud/ownCloud log
<details>

{"reqId":"Qd6RONbEa3JcHPGNJAJx","level":3,"time":"2021-12-27T16:52:13+00:00","remoteAddr":"181.137.36.16","user":"xxxxx","app":"PHP","method":"GET","url":"/index.php/apps/audioplayer/scanforaudiofiles?requesttoken=vo0JS68tFKfzbceuEPd31guyAAHabTTLrzH0XOnTbEQ%3D%3AlchQB5ZYI9C%2BC5GYWs8cu1%2F3WHigGmH%2BgGCBN4OaOzQ%3D","message":"Cannot modify header information - headers already sent by (output started at /snap/nextcloud/28715/htdocs/lib/private/legacy/OC_EventSource.php:111) at /snap/nextcloud/28715/htdocs/lib/private/AppFramework/Http/Output.php#70","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0","version":"22.2.3.0","exception":{"Exception":"Error","Message":"Cannot modify header information - headers already sent by (output started at /snap/nextcloud/28715/htdocs/lib/private/legacy/OC_EventSource.php:111) at /snap/nextcloud/28715/htdocs/lib/private/AppFramework/Http/Output.php#70","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/snap/nextcloud/28715/htdocs/lib/private/AppFramework/Http/Output.php","line":70,"function":"header"},{"file":"/snap/nextcloud/28715/htdocs/lib/private/AppFramework/App.php","line":165,"function":"setHeader","class":"OC\\AppFramework\\Http\\Output","type":"->"},{"file":"/snap/nextcloud/28715/htdocs/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/snap/nextcloud/28715/htdocs/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/snap/nextcloud/28715/htdocs/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/snap/nextcloud/28715/htdocs/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"Qd6RONbEa3JcHPGNJAJx","level":3,"time":"2021-12-27T16:52:13+00:00","remoteAddr":"181.137.36.16","user":"xxxxx","app":"PHP","method":"GET","url":"/index.php/apps/audioplayer/scanforaudiofiles?requesttoken=vo0JS68tFKfzbceuEPd31guyAAHabTTLrzH0XOnTbEQ%3D%3AlchQB5ZYI9C%2BC5GYWs8cu1%2F3WHigGmH%2BgGCBN4OaOzQ%3D","message":"Cannot modify header information - headers already sent by (output started at /snap/nextcloud/28715/htdocs/lib/private/legacy/OC_EventSource.php:111) at /snap/nextcloud/28715/htdocs/lib/private/AppFramework/Http/Output.php#70","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0","version":"22.2.3.0","exception":{"Exception":"Error","Message":"Cannot modify header information - headers already sent by (output started at /snap/nextcloud/28715/htdocs/lib/private/legacy/OC_EventSource.php:111) at /snap/nextcloud/28715/htdocs/lib/private/AppFramework/Http/Output.php#70","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/snap/nextcloud/28715/htdocs/lib/private/AppFramework/Http/Output.php","line":70,"function":"header"},{"file":"/snap/nextcloud/28715/htdocs/lib/private/AppFramework/App.php","line":165,"function":"setHeader","class":"OC\\AppFramework\\Http\\Output","type":"->"},{"file":"/snap/nextcloud/28715/htdocs/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/snap/nextcloud/28715/htdocs/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/snap/nextcloud/28715/htdocs/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/snap/nextcloud/28715/htdocs/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"Qd6RONbEa3JcHPGNJAJx","level":3,"time":"2021-12-27T16:52:13+00:00","remoteAddr":"181.137.36.16","user":"xxxxx","app":"PHP","method":"GET","url":"/index.php/apps/audioplayer/scanforaudiofiles?requesttoken=vo0JS68tFKfzbceuEPd31guyAAHabTTLrzH0XOnTbEQ%3D%3AlchQB5ZYI9C%2BC5GYWs8cu1%2F3WHigGmH%2BgGCBN4OaOzQ%3D","message":"Cannot modify header information - headers already sent by (output started at /snap/nextcloud/28715/htdocs/lib/private/legacy/OC_EventSource.php:111) at /snap/nextcloud/28715/htdocs/lib/private/AppFramework/Http/Output.php#70","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0","version":"22.2.3.0","exception":{"Exception":"Error","Message":"Cannot modify header information - headers already sent by (output started at /snap/nextcloud/28715/htdocs/lib/private/legacy/OC_EventSource.php:111) at /snap/nextcloud/28715/htdocs/lib/private/AppFramework/Http/Output.php#70","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/snap/nextcloud/28715/htdocs/lib/private/AppFramework/Http/Output.php","line":70,"function":"header"},{"file":"/snap/nextcloud/28715/htdocs/lib/private/AppFramework/App.php","line":165,"function":"setHeader","class":"OC\\AppFramework\\Http\\Output","type":"->"},{"file":"/snap/nextcloud/28715/htdocs/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/snap/nextcloud/28715/htdocs/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/snap/nextcloud/28715/htdocs/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/snap/nextcloud/28715/htdocs/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"Qd6RONbEa3JcHPGNJAJx","level":3,"time":"2021-12-27T16:52:13+00:00","remoteAddr":"181.137.36.16","user":"xxxxx","app":"PHP","method":"GET","url":"/index.php/apps/audioplayer/scanforaudiofiles?requesttoken=vo0JS68tFKfzbceuEPd31guyAAHabTTLrzH0XOnTbEQ%3D%3AlchQB5ZYI9C%2BC5GYWs8cu1%2F3WHigGmH%2BgGCBN4OaOzQ%3D","message":"Cannot modify header information - headers already sent by (output started at /snap/nextcloud/28715/htdocs/lib/private/legacy/OC_EventSource.php:111) at /snap/nextcloud/28715/htdocs/lib/private/AppFramework/Http/Output.php#70","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0","version":"22.2.3.0","exception":{"Exception":"Error","Message":"Cannot modify header information - headers already sent by (output started at /snap/nextcloud/28715/htdocs/lib/private/legacy/OC_EventSource.php:111) at /snap/nextcloud/28715/htdocs/lib/private/AppFramework/Http/Output.php#70","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/snap/nextcloud/28715/htdocs/lib/private/AppFramework/Http/Output.php","line":70,"function":"header"},{"file":"/snap/nextcloud/28715/htdocs/lib/private/AppFramework/App.php","line":165,"function":"setHeader","class":"OC\\AppFramework\\Http\\Output","type":"->"},{"file":"/snap/nextcloud/28715/htdocs/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/snap/nextcloud/28715/htdocs/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/snap/nextcloud/28715/htdocs/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/snap/nextcloud/28715/htdocs/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"Qd6RONbEa3JcHPGNJAJx","level":3,"time":"2021-12-27T16:52:13+00:00","remoteAddr":"181.137.36.16","user":"xxxxx","app":"PHP","method":"GET","url":"/index.php/apps/audioplayer/scanforaudiofiles?requesttoken=vo0JS68tFKfzbceuEPd31guyAAHabTTLrzH0XOnTbEQ%3D%3AlchQB5ZYI9C%2BC5GYWs8cu1%2F3WHigGmH%2BgGCBN4OaOzQ%3D","message":"Cannot modify header information - headers already sent by (output started at /snap/nextcloud/28715/htdocs/lib/private/legacy/OC_EventSource.php:111) at /snap/nextcloud/28715/htdocs/lib/private/AppFramework/Http/Output.php#70","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0","version":"22.2.3.0","exception":{"Exception":"Error","Message":"Cannot modify header information - headers already sent by (output started at /snap/nextcloud/28715/htdocs/lib/private/legacy/OC_EventSource.php:111) at /snap/nextcloud/28715/htdocs/lib/private/AppFramework/Http/Output.php#70","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/snap/nextcloud/28715/htdocs/lib/private/AppFramework/Http/Output.php","line":70,"function":"header"},{"file":"/snap/nextcloud/28715/htdocs/lib/private/AppFramework/App.php","line":205,"function":"setHeader","class":"OC\\AppFramework\\Http\\Output","type":"->"},{"file":"/snap/nextcloud/28715/htdocs/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/snap/nextcloud/28715/htdocs/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/snap/nextcloud/28715/htdocs/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/snap/nextcloud/28715/htdocs/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}

</details>

**Comment by Rello** [comment]
Hi
I just released a bugfix. Will show up shortly

**Comment by shamiv** [comment]
It works now, thanks a lot!
