### ISSUE TITLE
Song keeps loading until click on loading symbol[BUG] 

### ISSUE THREAD

**Issue by shamiv** [z000ao8q/audios#566]
**Describe the bug**
After clicking a song, the song keeps "loading" until I click on the "loading circle". Then the song starts playing.

**To Reproduce**

1. I search for an artist
2. I click on one of the "Audio Player" results 
3. I open an album of the Artist.
4. I click a song
5. The song keeps loading (does not play)
6. Until I click on the "loading circle". Song immediately starts playing.

**Expected behavior**

I would expect the song to play after step 4.

**Screenshots**

See [this](https://nextcloud.mishathings.com:9999/index.php/s/HRmxZit8yDnfZKP) screencast.

**Versions:**
 - Nextcloud:  22.2.3.0
 - Audioplayer: 3.2.4

**Comment by Rello** [comment]
oh. let me check.
thank you for the video!

**Comment by shamiv** [comment]
I think I have found the solution to the "problem". It occurs when I double click on the song. Clicking just once works fine. 

Maybe double clicking the song puts the song suspended between play and pause (or something like that?)

**Comment by Rello** [comment]
thats a nice find. sounds plausible.
will check how to handle this

**Comment by Rello** [comment]
3.3.0 released
