### ISSUE TITLE
[Feature Request] Artist/Title information from internet streams/playlists

### ISSUE THREAD

**Issue by JonTabor** [z000ao8q/audios#569]
In many external players (i.e. VLC, etc) the artist/title and/or stream information is displayed from an internet stream.  However, that information is not displayed in Audio Player.  I know extracting that is not trivial, but any possibility for it in the future?

**Comment by Rello** [comment]
Hello,
this is not planned. As my resources are limited due to other apps in parallel, I don´t have time to invest here.
The issue will be the access to external services which will expose the NC instance. I think this is not appreciated by many

Thank you,
Rello
