### ISSUE TITLE
drag and drop hover not accurate

### ISSUE THREAD

**Issue by CaviarTheCatgirl** [z000ao8q/audios#570]
**Describe the bug**
The Hitbox of playlists arent that accurate. Im using a 1080p Monitor and have Firefox on my Entire Screen (without Fullscreen) and it seems the "Hitbox" of where songs are added to Playlists are slightly off, too high above the actual playlist name

**To Reproduce**
1. Create a Playlist
2. Try to drag and drop a Song into it

**Expected behavior**
The hitbox to add the song to the Playlist should be perfectly aligned

**Screenshots**
https://cdn.discordapp.com/attachments/783653355158372357/947510387425837116/gif.gif

**Versions:**
 - Nextcloud: [e.g. 23.0.2]
 - Audioplayer [e.g. 3.2.4]

**Comment by Rello** [comment]
checking
thank you
the browses seem to handle this differently

**Comment by Rello** [comment]
I removed the old jquery stuff and migrated to html drag and drop api.
its working as expected now - and with even nicer visuals during the move.

**Comment by Rello** [comment]
3.3.0 released
