### ISSUE TITLE
Nextcloud - Code Signing - Audioplayer Fails Integrity Check

### ISSUE THREAD

**Issue by CloudServMan** [z000ao8q/audios#573]
### Actual behavior
After updating to Nextcloud 23.0.4 this morning, upon running Overview this is the result:
There are some errors regarding your setup.
Some files have not passed the integrity check. Further information on how to resolve this issue can be found in the documentation ↗. (List of invalid files… / Rescan…)

Nextcloud documentation says: For the "APP NAME" exception contact the developer of the application.

Before I remove signature.json, I felt it advisable to reach out to you for direction and advise.

Thanks

### Steps to reproduce the behavior
1. Click Overview in Settings
2. Click Overview in Settings
3. Click Overview in Settings

### Additional information (optional)

**Nextcloud/ownCloud version:** (see `/status.php`)
Nextcloud 23.0.4
**Audio Player version:** (see `/settings/apps`)
3.3.0
#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
Insert your Nextcloud/ownCloud log here
```

Below is the result of /settings/integrity/failed -
**Technical information

The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.
Results

    audioplayer
        EXTRA_FILE
            audioplayer/appinfo/signature.json
    bruteforcesettings
        EXTRA_FILE
            bruteforcesettings/appinfo/signature.json

Raw output

Array
(
[audioplayer] => Array
(
[EXTRA_FILE] => Array
(
[audioplayer/appinfo/signature.json] => Array
(
[expected] =>
[current] => bd05b8c3e9ce49392755a642d0189c01b1caecacd73eb7d0bdd83dd0b8853c02575a98692e5a34bc2df3a1e8525268db10914fb2fd18b74b9857482d702f9a53
)

            )

    )

[bruteforcesettings] => Array
    (
        [EXTRA_FILE] => Array
            (
                [bruteforcesettings/appinfo/signature.json] => Array
                    (
                        [expected] => 
                        [current] => 9b836bcde62ad8e166bec295f790cb8cc550079a5cbb1e93119878c8970c7f5b0a81c37cd36676a3ede60d7fd77747b1c521a5fe1fd51e0a13653d9bf250c96d
                    )

            )

    )

</details>

**Comment by Rello** [comment]
Hello,
do you still have this error?
with several 1000 installations, no one is reporting this. I expect this to be something local.
please get back if it is still existing
