### ISSUE TITLE
broken column layout in cover view

### ISSUE THREAD

**Issue by BigMichi1** [z000ao8q/audios#577]
**Describe the bug**
when an album contains more than 10 songs the title list is broken, see screenshots

**To Reproduce**
1. open an album 
2. See broken layout

**Expected behavior**
all titles should be properly displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/91786/180426082-4936afa4-e27f-4604-a158-dc04430ca9d0.png)

![image](https://user-images.githubusercontent.com/91786/180426141-9064e184-3f17-4a4a-ac9d-c18b7931a449.png)

**Versions:**
 - Nextcloud: 24.0.3
 - Audioplayer 3.3.0

**Comment by Rello** [comment]
found it. for some reason the `column-count` css is not working anymore?!

**Comment by Rello** [comment]
looking healthy again...
![Bildschirmfoto 2022-09-27 um 23 44 30](https://user-images.githubusercontent.com/13385119/192641395-bad80b6a-b71c-4ae9-b4f0-77e5b90fdcef.png)

**Comment by Rello** [comment]
tested in chrome, firefox & safari
