### ISSUE TITLE
[BUG] Incorrect display in the album explorer on Nextcloud AIO using Vivaldi web browser

### ISSUE THREAD

**Issue by EgonHeuson** [z000ao8q/audios#578]
**Describe the bug**
When opening an album in the application, the first few tracks are displayed correctly while the others seem to overlap (picture 1).
**/!\ This happens only with Vivaldi. Firefox works perfectly!**

**To Reproduce**
Simply upload an album, go to the audio app and click on the album image to expand it.

**Expected behavior**
All tracks are listed as in picture 3. This can be done by opening the tracks details in clicking on the 3 little dots (picture 2).

**Screenshots**
Picture 1:
<img width="1162" alt="2022-07-28_17-31-04" src="https://user-images.githubusercontent.com/32910291/181579562-b0a57e7b-3e70-40e3-b82a-e3471a1f6da3.png">

Picture 2:
<img width="1162" alt="2022-07-28_17-31-21" src="https://user-images.githubusercontent.com/32910291/181579595-1da214ee-5178-4213-8e08-b8f98651b45b.png">

Picture 3: 
<img width="1159" alt="2022-07-28_17-31-38" src="https://user-images.githubusercontent.com/32910291/181579616-7e6b6f7c-e2df-4601-bd8d-ee85e4acf8d6.png">

**Versions:**
 - Nextcloud AIO 1.6.0 (Nextcloud 24)
 - Audioplayer 3.3.0

**Comment by EgonHeuson** [comment]
Also, I can report that m4a file are not read using Vivaldi, while they play perfectly on Firefox. 🧐

**Comment by BigMichi1** [comment]
Also happens on Chrome #577

**Comment by EgonHeuson** [comment]
Yep. Actually, Vivaldi is using Chrome's engine as far I know, and same goes for it's extensions and etc. Therefore I'm not surprised ^^

**Comment by Rello** [comment]
Hello,
I need to check. did not even know that there is a "Vivaldi"...

**Comment by EgonHeuson** [comment]
Discovered it recently. It's the creator of the good old Opera (before i got acquired) that is now developing this web browser and I find it quite efficient actually. ☺️

**Comment by Rello** [comment]
solved with #577
