### ISSUE TITLE
[BUG] All m4a files are seen as broken, even if they don't seem broken and are played correctly on multiple devices

### ISSUE THREAD

**Issue by fabfabretti** [z000ao8q/audios#579]
Hi! I've been experiencing issues with m4a files, so I wanted to leave an issue to let you know. I've never opened one vefore, so I hope this is ok ^^

**Describe the bug**
As per title: when scanning for files, soundplayer app throws an error on all my m4a files and says they're broken, as rescanning doesn't solve the issue. However, the files play on both the NextCloud Files app player, my local player on my pc and also my phone; hence I don't understand how the files would be broken and if/how to fix the issue.

All these m4a files are downloads made with NewPipe and most are also tagged with AutomaTag. Both are Android apps.

**Expected behavior**
I'd expect the player to play these files, or to understand why they can't be played even if all other players do.

**Screenshots**
File working on my pc:
![immagine](https://user-images.githubusercontent.com/59342704/182051086-4153e3bc-cdac-49ee-95a1-cbb57bcb831e.png)
File working on nexctloud player inside Files app:
![immagine](https://user-images.githubusercontent.com/59342704/182051108-e3762067-70a7-4903-aab1-2269c059db6f.png)
File being detected as "broken" in audioplayer app:
![immagine](https://user-images.githubusercontent.com/59342704/182051147-9784cddc-f4a6-4576-af57-ce4fadfb4302.png)
![immagine](https://user-images.githubusercontent.com/59342704/182051166-1a6e8603-8a4a-462e-9c66-43a5a9270f88.png)

**Versions:**
 - Nextcloud: 24.0.3
 - Audioplayer 3.3.0
 

 Thank you a lot for your time, if you need more info feel free to ask.

**Comment by Rello** [comment]
hello @fabfabretti 
could you drop me one example file here, so I can check?
https://home.scherello.de/owncloud/s/JiFZYWzM6ZRrm47

**Comment by Rello** [comment]
just tried with a m4a testfile and it seems to work

**Comment by fabfabretti** [comment]
Hi, I'm really sorry for the delay. This is the exact file I showed in the issue.
https://mega.nz/file/6ApjjDJJ#sjtLre-JMQLN63Q3_B-zNBJb3-yPzvG4x3-kaBFHh-U

**Comment by Rello** [comment]
Hello,
thank you for this request. I understand the requirement, but the time invested in the app is currently limited due to other priorities.
