### ISSUE TITLE
[BUG] Not showing all album covers and scan errors...

### ISSUE THREAD

**Issue by XeonG** [z000ao8q/audios#580]
Is there something wrong with these files names,,..?

[![Foo](https://i.imgur.com/gbAbYea.png)](https://i.imgur.com/gbAbYea.png)

A folder with 1000+ songs is only showing like 7 albums with cover art, while the list view will show all the songs.. it's a bit annoying..  as the 'Files' view in will show all the mp3's with cover art, so I'm guessing it's the above scanning errors blocking it from finishing?

Also the the music player addon for nextcloud is showing the song covers..

**Comment by Rello** [comment]
Hi,
sorry for the delay...

so, all 1000 songs are scanned because you can see them in the `List` View in Audioplayer. is this correct?

in the `Album Covers` view plus the category "All Titels" selected, you only see some covers. is that correct?
This view is based on albums in general. do you have albums listed in the left navigation, when you select the category `Albums`?

some kind of screenshot could help.

the errors above should only show 6 specific files which have errors in their ID3 tags. this should not block the overall scanning

**Comment by XeonG** [comment]
Did another scan.. (Ihad a while back renamed the other files to remove the emojjies.. not that it made a difference... ![vivaldi_nM85yyA1Mh](https://user-images.githubusercontent.com/1556183/196524102-156ae437-c5f2-414f-9004-db066bfd9c4a.png)
![vivaldi_XdI3k4h2yG](https://user-images.githubusercontent.com/1556183/196524120-eb4dd872-2e6c-4e80-9df9-54fdb119c884.png)
![vivaldi_zwt8iKCrSr](https://user-images.githubusercontent.com/1556183/196524134-a68e9142-a7ca-4361-bef4-5835283ef3a3.png)

listview/ album view.. with folder selection.. can see most the songs aren't there..

interesting the other nextcloud 'Music' addon by Pauli Järvinen... the songs from that folder show album cover in the player bar(sadly the folder/album views kinda suck_..but  anyway it doesn't seem to be a problem with all the songs not having album covers.. because they all mostly do.

**Comment by XeonG** [comment]
@Rello ?

**Comment by Rello** [comment]
Hi,
the problem you have is the missing Album in the id3 tags if I am correct.
look at the list view. most of them have `Unknown`.
The graphical view sorts by albums - so if you would open the unknown generic icon, you would see 1000s titles there.
are you sure the ID3 tags are correct there?

**Comment by XeonG** [comment]
hmm that does add up.. so only 9 songs have album id ... so they get shown... ok that view kinda sucks then..  as most the songs in that folder all have image covers... but they are without album names as the id3 for album is empty...

could there be a better view added one that does List View with Thumbnails... or CoverView... I just want to see the covers for all songs in that folder 

or an option to  havev album view ignore empty id3

**Comment by Rello** [comment]
Hello,
thank you for this request. I understand the requirement, but the time invested in the app is currently limited due to other priorities.
