### ISSUE TITLE
[Feature Request] Dashboard Widget - Save last choice

### ISSUE THREAD

**Issue by florianwgnr** [z000ao8q/audios#582]
### Current behavior
After opening Nextcloud Dashboard, the Audio Player widget is empty and nothing is selected. Pressing "Play" does not play anything without selecting a category (e.g. Playlists) and an item (50 random tracks).

### Feature Request 
Save the last choice or make a preselection (e.g. playlist + 50 random tracks). After navigating to the dashboard, you can press "Play" and playback will start without having to select anything manually.

**Nextcloud/ownCloud version:** (see `/status.php`)
Nextcloud Version "24.0.5.1"
**Audio Player version:** (see `/settings/apps`)
Audio Player 3.3.1

**Comment by Rello** [comment]
Hello,
thank you for this request. I understand the requirement, but the time invested in the app is currently limited due to other priorities.

The feature is in general there. The app itself is using this, but it was not adopted to the Dashboard.
Suggestions welcome...
