### ISSUE TITLE
[BUG] Dashboard Widget - not playing pls playlists

### ISSUE THREAD

**Issue by kenda** [z000ao8q/audios#583]
**Describe the bug**
I have a couple of pls playlists which are working fine in the app itself. But they are not playing in the dashboard widget. 

I found this special handling here: https://github.com/Rello/audioplayer/blob/a7984dca1098bc1d58941e7b41fe333db93cacfe/js/dashboard.js#L355-L358 Which seems to handle the playlists like pls. Not sure if the `break` might be the problem already.

**Expected behavior**
After selecting a playlist, I should be able to play it.

**Versions:**
 - Nextcloud: 25.0.1
 - Audioplayer 3.3.1

**Comment by kenda** [comment]
I had a little look at it and it seems that the `break` is basically preventing the following CSP issue that the streams are not allowed because of the `media-src` CSP. The app itself is adding a wildcard here but I doubt that this is possible for the dashboard page.

**Comment by Rello** [comment]
thats correct here. the app itself can set alternative CSP - to do this for the dashboard, which includes other apps also, would be fatal
