### ISSUE TITLE
shuffle playlist button dosent work

### ISSUE THREAD

**Issue by meepcat55** [z000ao8q/audios#584]
when you press the button and play a playlist it dosent shuffle it

**To Reproduce**
press the shuffle playlist button
**Expected behavior**
it to shuffle the playlist

nextcloud rpi4 x64

**Comment by Rello** [comment]
Hi,
shuffle is only working in the list view. when pressing the button, it will shuffle the list. it will not remain highligted or so.
is this not working for you?
