### ISSUE TITLE
[Feature Request - Offtopic] Video Player prototype current state of afairs around nextcloud

### ISSUE THREAD

**Issue by ghost** [z000ao8q/audios#588]
**Describe the Problem **
Nextcloud is missing a reasonable features regarding video streaming (of entire folders) within the browser.
User currently need to rely on webdav and kodi etc

**Describe the solution you'd like**
for the beginning figuring out what it would take to get a very limited video player prototype.
I would be willing to help as much as i can after some guidance has been given (resources / repos), update on the current state of affairs regarding this topic etc
Since it would most likely require coding parts i can not preform within a reasonable time-span on my own due to my lack of experience in webdev regarding the implementation into nextcloud.

With how much money would it make your effort worth it outside of the community aspect in order to make a nextcloud video player prototype?

I would donate in parts after code being delivered and the first time in advance.

**Describe alternatives you've considered**
Wait longer

**Comment by Rello** [comment]
Hi,
Nextcloud has a basic video player out of the box.
To think about this is not related to this app here. The app has limited time invest at the moment as my priorities shifted to the Analytics app.
There will not be major enhancements here
